name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - develop

jobs:
  # 本番環境へのデプロイ用ジョブ
  deploy_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Inject Production Firebase Config
        run: |
          # 1. 本番用の合鍵を、一時ファイルに書き出す
          echo "const firebaseConfig = ${{ secrets.FIREBASE_CONFIG_PRODUCTION }};" > config.js # VSCode拡張機能からの警告を意図的に無視--> # yaml-language-server: ignore

          # 2. 全てのHTMLファイルで、目印の行を一時ファイルの中身に置き換える
          for file in *.html; do
            if grep -q "__FIREBASE_CONFIG__" "$file"; then
              sed -i -e '/__FIREBASE_CONFIG__/r config.js' -e '/__FIREBASE_CONFIG__/d' "$file"
            fi
          done
      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP }}' # VSCode拡張機能からの警告を意図的に無視--> # yaml-language-server: ignore
          projectId: aac-label-check-app
          channelId: live

  # テスト環境へのデプロイ用ジョブ
  deploy_development:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Inject Development Firebase Config
        run: |
          # 1. テスト用の合鍵を、一時ファイルに書き出す
          echo "const firebaseConfig = ${{ secrets.FIREBASE_CONFIG_DEVELOPMENT }};" > config.js # VSCode拡張機能からの警告を意図的に無視--> # yaml-language-server: ignore

          # 2. 全てのHTMLファイルで、目印の行を一時ファイルの中身に置き換える
          for file in *.html; do
            if grep -q "__FIREBASE_CONFIG__" "$file"; then
              sed -i -e '/__FIREBASE_CONFIG__/r config.js' -e '/__FIREBASE_CONFIG__/d' "$file"
            fi
          done
      - name: Deploy to Firebase Hosting (Development)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP_DEV }}' # VSCode拡張機能からの警告を意図的に無視--> # yaml-language-server: ignore
          projectId: aac-label-check-app-dev
          channelId: live
