name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - develop

jobs:
  # 本番環境へのデプロイ用ジョブ
  deploy_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Inject Production Firebase Config
        # 英語: Inject the Firebase config JSON into each HTML file.
        # 和訳: Firebaseの設定情報を各HTMLファイルに埋め込みます。
        run: |
          CONFIG_JSON='${{ secrets.FIREBASE_CONFIG_PRODUCTION }}'
          for file in *.html; do
            if grep -q "__FIREBASE_CONFIG__" "$file"; then
              # 'sed'の代わりに'awk'を使い、特殊文字を含む変数を安全に置換します。
              # Using 'awk' instead of 'sed' to safely replace variables containing special characters.
              awk -v config="${CONFIG_JSON}" '{gsub(/__FIREBASE_CONFIG__/, config)}1' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            fi
          done
      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP }}'
          projectId: aac-label-check-app
          channelId: live

  # テスト環境へのデプロイ用ジョブ
  deploy_development:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Inject Development Firebase Config
        # 英語: Inject the Firebase config JSON into each HTML file.
        # 和訳: Firebaseの設定情報を各HTMLファイルに埋め込みます。
        run: |
          CONFIG_JSON='${{ secrets.FIREBASE_CONFIG_DEVELOPMENT }}'
          for file in *.html; do
            if grep -q "__FIREBASE_CONFIG__" "$file"; then
              # 'sed'の代わりに'awk'を使い、特殊文字を含む変数を安全に置換します。
              # Using 'awk' instead of 'sed' to safely replace variables containing special characters.
              awk -v config="${CONFIG_JSON}" '{gsub(/__FIREBASE_CONFIG__/, config)}1' "$file" > "$file.tmp" && mv "$file.tmp" "$file"
            fi
          done
      - name: Deploy to Firebase Hosting (Development)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP_DEV }}'
          projectId: aac-label-check-app-dev
          channelId: live