name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - develop

jobs:
  # 本番環境へのデプロイ用ジョブ
  deploy_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production # 本番用の金庫(Environment)を指定
    steps:
      - uses: actions/checkout@v3

      - name: Inject Production Firebase Config
        run: |
          # 合鍵を一時ファイルに書き出す
          echo "const firebaseConfig = ${{ secrets.FIREBASE_CONFIG_PRODUCTION }};" > config.js

          # 全てのHTMLファイルで、目印の行を一時ファイルの中身に置き換える
          for file in *.html; do
            if grep -q "const firebaseConfig = {};" "$file"; then
              sed -i -e '/const firebaseConfig = {};/r config.js' -e '/const firebaseConfig = {};/d' "$file"
            fi
          done

      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP }}'
          projectId: aac-label-check-app
          channelId: live

  # テスト環境へのデプロイ用ジョブ
  deploy_development:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development # テスト用の金庫(Environment)を指定
    steps:
      - uses: actions/checkout@v3

      - name: Inject Development Firebase Config
        run: |
          # 合鍵を一時ファイルに書き出す
          echo "const firebaseConfig = ${{ secrets.FIREBASE_CONFIG_DEVELOPMENT }};" > config.js

          # 全てのHTMLファイルで、目印の行を一時ファイルの中身に置き換える
          for file in *.html; do
            if grep -q "const firebaseConfig = {};" "$file"; then
              sed -i -e '/const firebaseConfig = {};/r config.js' -e '/const firebaseConfig = {};/d' "$file"
            fi
          done

      - name: Deploy to Firebase Hosting (Development)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP_DEV }}'
          projectId: aac-label-check-app-dev
          channelId: live
