name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - develop

jobs:
  # 本番環境へのデプロイ用ジョブ
  deploy_production:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - name: Inject Production Firebase Config
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_PRODUCTION }}
        run: |
          for file in *.html; do
            if grep -q "const firebaseConfig = {};" "$file"; then
              echo "const firebaseConfig = ${FIREBASE_CONFIG};" > config.js
              sed -i -e '/const firebaseConfig = {};/r config.js' -e '/const firebaseConfig = {};/d' "$file"
            fi
          done
      - name: Deploy to Firebase Hosting (Production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP }}'
          projectId: aac-label-check-app
          channelId: live

  # テスト環境へのデプロイ用ジョブ
  deploy_development:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - name: Inject Development Firebase Config
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG_DEVELOPMENT }}
        run: |
          for file in *.html; do
            if grep -q "const firebaseConfig = {};" "$file"; then
              echo "const firebaseConfig = ${FIREBASE_CONFIG};" > config.js
              sed -i -e '/const firebaseConfig = {};/r config.js' -e '/const firebaseConfig = {};/d' "$file"
            fi
          done
      - name: Deploy to Firebase Hosting (Development)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_AAC_LABEL_CHECK_APP_DEV }}'
          projectId: aac-label-check-app-dev
          channelId: live
